### ISSUE TITLE
Sharp and Flat modifiers overlapping depending on width

### ISSUE THREAD

**Issue by AllanMartel** [MrUnknown404/Project-Spear#1]
**Describe the bug**
Sharp and Flat modifiers overlapping with other objects

**To Reproduce**
Open it up and look at any level above 5

**Expected behavior**
 

**Screenshots**
 
**Additional context**
 Perhaps if the modifier is moved into the center off the note on the scale?

**Comment by MrUnknown404** [comment]
This has been fixed in V7+
